apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster
  region: ap-southeast-2
  version: "1.14"

vpc:
  subnets:
    private:
      us-west-2a:
        id: "Quick-Start-VPC-PrivateSubnet1AID"
      us-west-2b:
        id: "Quick-Start-VPC-PrivateSubnet2AID"
      us-west-2c:
        id: "Quick-Start-VPC-PrivateSubnet3AID"
    public:
      us-west-2a:
        id: "Quick-Start-VPC-PublicSubnet1ID"
      us-west-2b:
        id: "Quick-Start-VPC-PublicSubnet2ID"
      us-west-2c:
        id: "Quick-Start-VPC-PublicSubnet3ID"

cloudWatch:
    clusterLogging:
        enableTypes: ["*"]

nodeGroups:
  - name: ng
    instanceType: m5.xlarge
    desiredCapacity: 1
    privateNetworking: true
    volumeSize: 100
    volumeType: gp2
    volumeEncrypted: true
    ssh:
      publicKeyPath: ~/.ssh/id_rsa.pub
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        certManager: true
        appMesh: true
        ebs: true
        fsx: true
        efs: true
        albIngress: true
        xRay: true
        cloudWatch: true